import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Nunito_Sans, Inter_Tight, Inter, Manrope } from "@next/font/google";
import { Poppins, Nunito_Sans, Inter } from "next/font/google";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const nunitosans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-nunito-sans",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

// const inter = Inter_Tight({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-interG",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nunitosans.variable} antialiased text-stone-950 bg-stone-100`}
      >
        {children}
      </body>
    </html>
  );
}
